# Generated by Django 2.2.2 on 2019-07-06 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='photo_1',
            new_name='photo_main',
        ),
    ]
